In [1]:
                                    import the numpy package under the name np
import numpy as np

In [3]:
np.zeros(10)                        create a null vector of size 10
        

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array=np.arange(10,49)          create a vec with values ranging from 10 to 49

In [10]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [11]:
array.shape                        find the shape of previous array

(39,)

In [12]:
array.dtype                       print the type of previous array

dtype('int32')

In [13]:
print(np.__version__)             print the numpy version

1.18.1


In [15]:
array.ndim                        print the dimension of the array

1

In [17]:
array1=np.zeros((2,2))            create a two dimensional array

In [18]:
array1

array([[0., 0.],
       [0., 0.]])

In [21]:
array2=np.zeros((3,3,3))         create a three dimensional array

In [26]:
array2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
array=np.zeros(10)         create a null vec of size 10 but the fifth value is 1

In [40]:
array[4]=1

In [42]:
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [43]:
matrix=np.identity(3)       create a 3 by 3 identity matrix

In [44]:
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arr=np.array([1,2,3,4,5])     convert this datatype array into float

In [46]:
arr.astype(np.float)

array([1., 2., 3., 4., 5.])

In [47]:
array1=([[1.,2.,3.,4.,5.,6.]])
array2=([[0.,4.,1.,7.,2.,12.]])      multiply array1 with array2

In [48]:
np.multiply(array1,array2)

array([[ 0.,  8.,  3., 28., 10., 72.]])

In [50]:
arr=np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12            replace the values of indexes 5,6,7 and 8 to 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [51]:
array=np.ones((8,8))
array[1:-1,1:-1]=0
array                               create a 2d array with 1 on the border and 0 inside

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
arr2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])                 replace the value 5 to 12
                
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [59]:
a=np.array([1,2,3,2,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])      find the common items between a & b
np.intersect1d(a,b)

array([2, 4])

In [63]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])   find the unique names and sort them out


In [67]:
np.unique(names)

array(['bob', 'joe', 'will'], dtype='<U4')

In [68]:
x=np.array([[1.,2.,3.],      find the dot product of the given two matrix 
            [4.,5.,6.]])
y=np.array([[6.,23.],
            [-1,7],
            [8,9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])